name: ML Model Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'models/**'
      - 'src/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'models/**'
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Build model
        run: python src/build_model.py
        
      - name: Upload model artifact
        uses: actions/upload-artifact@v3
        with:
          name: model-artifact
          path: build/model.*
          
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Download model artifact
        uses: actions/download-artifact@v3
        with:
          name: model-artifact
          path: build/
          
      - name: Test model
        run: python src/test_model.py
        
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/test_results.json
          
  evaluate:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Download test results
        uses: actions/download-artifact@v3
        with:
          name: test-results
          path: build/
          
      - name: Evaluate model
        run: python src/evaluate_model.py
        
      - name: Upload evaluation report
        uses: actions/upload-artifact@v3
        with:
          name: evaluation-report
          path: build/evaluation_report.json
          
  compare:
    needs: evaluate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Download evaluation report
        uses: actions/download-artifact@v3
        with:
          name: evaluation-report
          path: build/
          
      - name: Compare with previous model
        run: python src/compare_models.py
        
      - name: Upload comparison report
        uses: actions/upload-artifact@v3
        with:
          name: comparison-report
          path: build/comparison_report.json

  deploy:
    needs: compare
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Download model artifact
        uses: actions/download-artifact@v3
        with:
          name: model-artifact
          path: build/
          
      - name: Deploy model
        run: python src/deploy_model.py