# Configuration du modèle - Version 1.0.0
model:
  name: "ClassifierModel"
  version: "1.0.0"
  type: "classification"
  algorithm: "random_forest"

parameters:
  n_estimators: 100
  max_depth: 10
  min_samples_split: 2
  min_samples_leaf: 1

training:
  epochs: 100
  batch_size: 32
  learning_rate: 0.001
  validation_split: 0.2

evaluation:
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1"

data:
  train_path: "data/classification_train.csv"
  test_path: "data/classification_test.csv"
  test_split: 0.1
  validation_split: 0.2
